/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.individual;

import java.util.Random;

/**
 *
 * @author paula
 */
public class Monitoramento extends javax.swing.JFrame {
    Integer contador = 0;
    Integer somaCPU = 0;
    Integer maximoCPU = 0;
    Integer minimoCPU = 100;
    Integer somaDisco = 0;
    Integer maximoDisco = 0;
    Integer minimoDisco = 100;
    Integer somaMemoria = 0;
    Integer maximoMemoria = 0;
    Integer minimoMemoria = 100;
    /**
     * Creates new form Monitoramento
     */
    public Monitoramento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barCPU = new javax.swing.JProgressBar();
        barDisco = new javax.swing.JProgressBar();
        barMemoria = new javax.swing.JProgressBar();
        lblCPU = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        btnLeitura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblValorSorteadoCPU = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblValorSorteadoDisco = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblValorSorteadoMemoria = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblValorMaximoCPU = new javax.swing.JLabel();
        lblValorMinimoCPU = new javax.swing.JLabel();
        lblMediaCPU = new javax.swing.JLabel();
        lblValorMaximoDisco = new javax.swing.JLabel();
        lblValorMinimoDisco = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        lblValorMaximoMemoria = new javax.swing.JLabel();
        lblValorMinimoMemoria = new javax.swing.JLabel();
        lblMediaMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCPU.setText("CPU");

        lblDisco.setText("Disco");

        lblMemoria.setText("Memória");

        btnLeitura.setText("Fazer leitura dos dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor");

        lblValorSorteadoCPU.setText("A sortear");

        jLabel6.setText("Valor");

        lblValorSorteadoDisco.setText("A sortear");

        jLabel8.setText("Valor");

        lblValorSorteadoMemoria.setText("A sortear");

        jLabel10.setText("Máximo");

        jLabel11.setText("Mínimo");

        jLabel12.setText("Média");

        jLabel13.setText("Máximo");

        jLabel14.setText("Mínimo");

        jLabel15.setText("Média");

        jLabel16.setText("Máximo");

        jLabel17.setText("Mínimo");

        jLabel18.setText("Média");

        lblValorMaximoCPU.setText("A sortear");

        lblValorMinimoCPU.setText("A sortear");

        lblMediaCPU.setText("A sortear");

        lblValorMaximoDisco.setText("A sortear");

        lblValorMinimoDisco.setText("A sortear");

        lblMediaDisco.setText("A sortear");

        lblValorMaximoMemoria.setText("A sortear");

        lblValorMinimoMemoria.setText("A sortear");

        lblMediaMemoria.setText("A sortear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblCPU)
                .addGap(315, 315, 315)
                .addComponent(lblDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMemoria)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLeitura)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorSorteadoDisco)
                                    .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValorMaximoDisco)
                                    .addComponent(lblValorMinimoDisco)
                                    .addComponent(lblMediaDisco)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMediaCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorMinimoCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorSorteadoCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorMaximoCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(barMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorSorteadoMemoria)
                            .addComponent(lblValorMaximoMemoria)
                            .addComponent(lblValorMinimoMemoria)
                            .addComponent(lblMediaMemoria))
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPU)
                    .addComponent(lblDisco)
                    .addComponent(lblMemoria))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblValorSorteadoCPU)
                    .addComponent(jLabel6)
                    .addComponent(lblValorSorteadoDisco)
                    .addComponent(jLabel8)
                    .addComponent(lblValorSorteadoMemoria))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(lblValorMaximoCPU)
                    .addComponent(lblValorMaximoDisco)
                    .addComponent(lblValorMaximoMemoria))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(lblValorMinimoCPU)
                    .addComponent(lblValorMinimoDisco)
                    .addComponent(lblValorMinimoMemoria))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(lblMediaCPU)
                    .addComponent(lblMediaDisco)
                    .addComponent(lblMediaMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnLeitura)
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
        // TODO add your handling code here:
        contador ++;
        
        Random aleatorioCPU = new Random();
        Integer sorteadoCPU = aleatorioCPU.nextInt(101);
        String sorteadoCPUTexto = sorteadoCPU.toString();
        lblValorSorteadoCPU.setText(sorteadoCPUTexto);
        barCPU.setValue(sorteadoCPU);
        if (sorteadoCPU > maximoCPU ) {
            maximoCPU = sorteadoCPU;
            lblValorMaximoCPU.setText(maximoCPU.toString());
        }
        if (sorteadoCPU < minimoCPU) {
            minimoCPU = sorteadoCPU; 
            lblValorMinimoCPU.setText(minimoCPU.toString());
        }
        somaCPU = somaCPU + sorteadoCPU;
        Integer mediaCPU = somaCPU/contador;
        lblMediaCPU.setText(mediaCPU.toString());
        
        Random aleatorioDisco = new Random();
        Integer sorteadoDisco = aleatorioDisco.nextInt(101);
        String sorteadoDiscoTexto = sorteadoDisco.toString();
        lblValorSorteadoDisco.setText(sorteadoDiscoTexto);
        barDisco.setValue(sorteadoDisco);
        if (sorteadoDisco > maximoDisco ) {
            maximoDisco = sorteadoDisco;
            lblValorMaximoDisco.setText(maximoDisco.toString());
        }
        if (sorteadoDisco < minimoDisco) {
            minimoDisco = sorteadoDisco; 
            lblValorMinimoDisco.setText(minimoDisco.toString());
        }
        somaDisco = somaDisco + sorteadoDisco;
        Integer mediaDisco = somaDisco/contador;
        lblMediaDisco.setText(mediaDisco.toString());
        
        
        Random aleatorioMemoria = new Random();
        Integer sorteadoMemoria = aleatorioMemoria.nextInt(101);
        String sorteadoMemoriaTexto = sorteadoMemoria.toString();
        lblValorSorteadoMemoria.setText(sorteadoMemoriaTexto);
        barMemoria.setValue(sorteadoMemoria);
        if (sorteadoMemoria > maximoMemoria ) {
            maximoMemoria = sorteadoMemoria;
            lblValorMaximoMemoria.setText(maximoMemoria.toString());
        }
        if (sorteadoMemoria < minimoMemoria) {
            minimoMemoria = sorteadoMemoria; 
            lblValorMinimoMemoria.setText(minimoMemoria.toString());
        }
        somaMemoria = somaMemoria + sorteadoMemoria;
        Integer mediaMemoria = somaMemoria/contador;
        lblMediaMemoria.setText(mediaMemoria.toString());
        
        
    }//GEN-LAST:event_btnLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCPU;
    private javax.swing.JProgressBar barDisco;
    private javax.swing.JProgressBar barMemoria;
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMediaCPU;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaMemoria;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblValorMaximoCPU;
    private javax.swing.JLabel lblValorMaximoDisco;
    private javax.swing.JLabel lblValorMaximoMemoria;
    private javax.swing.JLabel lblValorMinimoCPU;
    private javax.swing.JLabel lblValorMinimoDisco;
    private javax.swing.JLabel lblValorMinimoMemoria;
    private javax.swing.JLabel lblValorSorteadoCPU;
    private javax.swing.JLabel lblValorSorteadoDisco;
    private javax.swing.JLabel lblValorSorteadoMemoria;
    // End of variables declaration//GEN-END:variables
}
